<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();

        ?><ul class="products-grid row">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php
                    /* if ($i++%$_columnCount==0): ?>
                     <ul class="products-grid row">
                    <?php endif */
                ?>
                <li class="item <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>  col-sm-4 col-xs-6">
                    <div class="heart-it">
                        <span>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist">
                                    <img alt="<?php echo $this->__('Add to Wishlist')?>" src="<?php echo $this->getSkinUrl('images/svg/heart.svg');?>" >
                                </a>
                            <?php endif; ?>
                        </span>
                    </div>
                    <div class="compare-it">
                       <span>
                            <a href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_product) ?>">
                                <img alt="<?php echo $this->__('Add to Compare') ?>" src="<?php echo $this->getSkinUrl('images/svg/compare.svg'); ?>" />
                            </a>
                        </span>
                    </div>

                    <div class="item-container img-thumbnail">
                        <div class="item-flipper">
                            <div class="item-front">
                                <!-- front content -->
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,310); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive" /></a>
                            </div>
                            <div class="item-back">
                                Back informations....
                            </div>

                            <div class="item-actions">
                                <!-- back content -->
                                <div class="product-info">
                                    <div class="grid-product-title">
                                        <h4>
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                            <?php echo $this->getPriceHtml($_product, true) ?>
                                        </h4>
                                    </div>
                                    <div class="product-actions">
                                        <ul class="product-buttons">
                                            <li class="pull-right grid-product-addtocart">
                                                <?php if($_product->isSaleable()): ?>
                                                    <!-- <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-prod-grid btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>-->
                                                    <a class="btn btn-prod-grid btn-cart" href="javascript:void(0) onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')""><?php echo $this->__('Add to Cart') ?></a>
                                                <?php else: ?>
                                                    <p class="btn btn-alert availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                <?php endif; ?>
                                            </li>
                                            <li class="pull-right grid-product-prod-view">
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="btn btn-prod-grid"><?php echo $this->__('More Details')?></a>
                                            </li>
                                        </ul>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </li>
                <?php if ($i==6) break; ?>
                <?php /*  if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif */ ?>
            <?php endforeach ?></ul>
    </div>
<?php endif; ?>


<script type="text/javascript">
    //<![CDATA[
        $(function() {
        $('.item').matchHeight(
            {
                byRow: true,
                property: 'height',
                remove: true
            }
        );
        });
    $(function() {
        $(".item").hover(
            function () {
                $(".heart-it").show();
            },function () {
                $(".heart-it").hide();
            }
        );
    });

    //]]>
</script>
