<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();

        ?><ul class="products-grid row">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php
                /* if ($i++%$_columnCount==0): ?>
                 <ul class="products-grid row">
                <?php endif */
                ?>
                <li class="item homepage-item <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>  col-sm-4 col-xs-6">
<!--                    <div class="heart-it">-->
<!--                        <span>-->
<!--                            --><?php //if ($this->helper('wishlist')->isAllow()) : ?>
<!--                                <a href="--><?php //echo $_wishlistSubmitUrl ?><!--" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist">-->
<!--                                    <img alt="--><?php //echo $this->__('Add to Wishlist')?><!--" src="--><?php //echo $this->getSkinUrl('images/svg/heart.svg');?><!--" >-->
<!--                                </a>-->
<!--                            --><?php //endif; ?>
<!--                        </span>-->
<!--                    </div>-->
<!--                    <div class="compare-it">-->
<!--                       <span>-->
<!--                            <a href="--><?php //echo $this->helper('catalog/product_compare')->getAddUrl($_product) ?><!--">-->
<!--                                <img alt="--><?php //echo $this->__('Add to Compare') ?><!--" src="--><?php //echo $this->getSkinUrl('images/svg/compare.svg'); ?><!--" />-->
<!--                            </a>-->
<!--                        </span>-->
<!--                    </div>-->

                    <div class="item-container img-thumbnail">
                        <div class="item-flipper">
                            <div class="item-front">
                                <!-- front content -->
<!--                                <a href="--><?php //echo $_product->getProductUrl() ?><!--" title="--><?php //echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?><!--" class="product-image"><img src="--><?php //echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,310); ?><!--" alt="--><?php //echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?><!--" class="img-responsive" /></a>-->

                            <!--Image flipper start-->
                                <div class="item-container img-thumbnail">
                                    <div class="item-flipper">
                                        <div class="item-front">
                                            <!-- front content -->
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                <img
                                                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,310); ?>"
                                                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'),null, true) ?>" class="img-responsive" />
                                            </a>
                                        </div>
                                        <div class="item-back">
                                            <!-- back content -->
                                            <div class="book-info">
                                                <div class="h4">
                                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                                    </a>
                                                </div>
                                                <div class="short-description">
                                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                </div>

                                            </div>
                                            <p>
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(),null, true) ?>" class="btn btn-block btn-success">
                                                    <?php echo $this->__('Book Details')?>
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            <!--Image flipper ends-->


                            </div>
                            <div class="item-back">
                                Back informations....
                            </div>

                            <div class="item-actions">
                                <!-- back content -->
                                <div class="product-info">
                                    <div class="grid-product-title">
                                        <h4>
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                            <?php echo $this->getPriceHtml($_product, true) ?>
                                        </h4>
                                    </div>


                                </div>

                            </div>
                        </div>
                    </div>
                </li>
                <?php if ($i==6) break; ?>
                <?php /*  if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif */ ?>
            <?php endforeach ?></ul>
    </div>
<?php endif; ?>

